### ISSUE TITLE
'uk-upper-tier-local-authorities.hexjson' isn't as described

### ISSUE THREAD

**Issue by philipnye** [odileeds/hexmaps#10]
The file `https://github.com/odileeds/hexmaps/blob/gh-pages/maps/uk-upper-tier-local-authorities.hexjson` gives hexjson data on what looks to be a strange mash-up of upper-tier LA data and...something else

Examples:

- Greater Manchester, rather than Bury, Bolton, Oldham etc.

- Inner London and Outer London, rather than constituent boroughs

The file `https://github.com/odileeds/hexmaps/blob/gh-pages/maps/uk-covid-19.hexjson` seems to contain what are correctly upper-tier LAs for England.

**Comment by philipnye** [comment]
I've created a replacement in pull request #12

**Comment by slowe** [comment]
We need to add in Wales, Scotland, and Northern Ireland.
