### ISSUE TITLE
Review 2023 UK Local Authority layout

### ISSUE THREAD

**Issue by slowe** [odileeds/hexmaps#19]
A first attempt at defining the layout for 2023 UK Local Authorities has been done. This took [the changes listed on Wikipedia](https://en.wikipedia.org/wiki/2019%E2%80%932023_structural_changes_to_local_government_in_England) (around Cumbria, North Yorkshire and Somerset) and the [ONS codes](https://geoportal.statistics.gov.uk/datasets/ons::local-authority-districts-april-2023-names-and-codes-in-the-united-kingdom/about) for the new authorities. The changes basically combine several already geographically-large local authorities into even larger ones. This has meant the hex layout is now trickier in the South West, and much of the North of England.

**Comment by slowe** [comment]
@ODILMichelle Losing three hexes has had a knock on affect on the South West and could do with your review. It won't be possible to have everything that should be coastal on the coast, unfortunately. And some neighbours will have to be disconnected in places. We should try to maintain a familiar shape to the overall region.

You can view the layout in the Hexmap Builder tool with hexes colour coded by region https://open-innovations.org/projects/hexmaps/builder.html?maps/uk-local-authority-districts-2023.hexjson The Builder will also let you move hexes around. It doesn't automatically save changes so if you create a better layout make sure to click the "HexJSON" button at the bottom to save the file and then update the repo file at https://github.com/odileeds/hexmaps/blob/gh-pages/maps/uk-local-authority-districts-2023.hexjson

**Comment by ODILMichelle** [comment]
Hey @slowe thanks for this. Is there a specific deadline/time-frame this is needed in?

**Comment by slowe** [comment]
No.

**Comment by slowe** [comment]
Nobody reviewed it but we are using it anyway.
