### ISSUE TITLE
2023 Constituency Boundries

### ISSUE THREAD

**Issue by jms301** [odileeds/hexmaps#20]
Is anyone working on a hex layout for the new Westminster Constituency Boundaries? 

If not I might get round to making one myself in which case is this the right place to submit a pull request to?

**Comment by slowe** [comment]
We haven't started doing that yet partly because we were waiting on final decisions and because there are no (as far as I can tell) ONS codes for the new constituencies yet. However the plan is to start making a draft soon.

**Comment by slowe** [comment]
@jms301 OK. Here's the first draft of a 2023 boundaries HexJSON layout https://github.com/odileeds/hexmaps/blob/gh-pages/maps/uk-constituencies-2023.hexjson you can [play about with that file using our hex builder tool](https://open-innovations.org/projects/hexmaps/builder.html?https://raw.githubusercontent.com/odileeds/hexmaps/gh-pages/maps/uk-constituencies-2023.hexjson)

**Comment by slowe** [comment]
@davidtreth Hi. You really helped improve the layout of the South West back in 2019. Now that constituencies are changing, we've had to start over with most of the layout. Would you be able to have a look at [our new draft layout](https://open-innovations.org/projects/hexmaps/builder.html?https://raw.githubusercontent.com/odileeds/hexmaps/gh-pages/maps/uk-constituencies-2023.hexjson) with [the new boundaries](https://alasdairrae.github.io/wpc2023/#8/50.686/-3.801)? I've done my best but obviously I don't have a feel for the SW like you do so it'd be great to have your input.
