### ISSUE TITLE
2019 LA mergers

### ISSUE THREAD

**Issue by gwilymlockwood** [odileeds/hexmaps#5]
Some English LAs are out of date due to mergers which happened in 2018 and 2019. Here are the ones I've found - there may be more, including in Wales/Scotland/NI which I haven't spotted.

Taunton Deane (E07000190) and West Somerset (E07000191)
--> Somerset West and Taunton (E07000246)

Bournemouth (E06000028), Poole (E06000029), and Christchurch (E07000048)
--> Bournemouth, Christchurch and Poole (E06000058)

Weymouth and Portland (E07000053), West Dorset (E07000052), East Dorset (E07000049), North Dorset (E07000050), and Purbeck (E07000051)
--> Dorset (E06000059)

Forest Heath (E07000201) and St. Edmundsbury (E07000204)
--> East Suffolk (E07000244)

Waveney (E07000206) and Suffolk Coastal (E07000205)
--> West Suffolk (E07000244)

Rather than changing the current version, it would be nice to one set of hexes for the 2017-18 LAs and a new set of hexes for the 2019 LAs. There's ONS data across the old LAs and the new LAs, so it would be good to have both options for mapping depending on the dataset I'm using at the time.

(apologies if this issue isn't written up correctly - I never really use GitHub, so I'm not sure if I'm accidentally not adhering to posting etiquette)

**Comment by slowe** [comment]
Thanks for pointing this out @gflockwood. I started from the ONS's latest (April 2019) geography and recreated the map. The South West and East of England are where most of the changes seem to be. A [draft 2019 version is now available](https://odileeds.org/projects/hexmaps/builder?https://odileeds.github.io/hexmaps/maps/uk-local-authority-districts-2019.hexjson). If it doesn't feel quite right, that link should let you move hexes around to make it better. If you do edit it you can then save the hexjson, update [the hexjson](https://github.com/odileeds/hexmaps/blob/gh-pages/maps/uk-local-authority-districts-2019.hexjson) and create a pull request.

**Comment by gwilymlockwood** [comment]
Thanks @slowe, it looks good!
